add crate packaging script (just untar dist)

diff --git a/packages/crate/packaging b/packages/crate/packaging
--- a/packages/crate/packaging
+++ b/packages/crate/packaging
@@ -8,4 +8,15 @@ CPUS=$(grep -c ^processor /proc/cpuinfo)
 # $BOSH_INSTALL_TARGET - where you copy/install files to be included in package
 export HOME=/var/vcap
 
+CRATE_VERSION="0.55.3"
+tar xzvf ${BOSH_COMPILE_TARGET}/crate/crate-${CRATE_VERSION}.tar.gz
+if [[ $? != 0 ]] ; then
+  echo "Failed extracting Crate ${CRATE_VERSION}"
+  exit 1
+fi
+
+# Copy Crate package
+echo "Copying Crate ${CRATE_VERSION}..."
+cp -a ${BOSH_COMPILE_TARGET}/crate-${CRATE_VERSION}/* ${BOSH_INSTALL_TARGET}/
+
 
